### ISSUE TITLE
A02s support

### ISSUE THREAD

**Issue by RandomUser1321** [ravindu644/twrp_galaxy_m02s#4]
Coming from a A02s Im trying to find a twrp for the A02s for some time and I wonder if it has support for the A02s

**Comment by RandomUser1321** [comment]
So update I have gathered the courage to try it and I can boots to recovery but touch doesnt work and I cant reboot back to download help

**Comment by RandomUser1321** [comment]
I got the phone turned off and tried going back to twrp touch still doesnt work and actually recognizes as a M02s (im not stupid Im sure its an A02s)

**Comment by ravindu644** [comment]
> I got the phone turned off and tried going back to twrp touch still doesnt work and actually recognizes as a M02s (im not stupid Im sure its an A02s)

You should check out this & start issues in there. (because I don't have these devices to test) :

https://github.com/mlm-games/twrp_galaxy_m02s

**Comment by RandomUser1321** [comment]
Hello I realised the twrp file mentioned was a IMG file so after using winrar to change it to tar odin gets stuck at file analysis (I tried rebooting the phone and plus I tried 3 times)

**Comment by RandomUser1321** [comment]
I cant start issues there theres only an option to pull request btw I cant get that img to work I always try to archive it as tar and flash with odin and it gets stuck on file analysis

**Comment by mlm-games** [comment]
Um i had noticed the merge request was merged... 
It was actually done by mistake as i was again tring to merge 2 branches like previously so didnt change the title of my MR


> So update I have gathered the courage to try it and I can boots to recovery but touch doesnt work and I cant reboot back to download help

Did u try checking touch after waiting 5 secs with screen off and then turning on?


> I cant start issues there theres only an option to pull request btw I cant get that img to work I always try to archive it as tar and flash with odin and it gets stuck on file analysis

Oh ye, i didnt notice issues were not present when i asked for support on A02s in readme, mb. Enabled them now.
May i know what u did after unlocking ur bootloader exactly and also just try flashing the clean vbmeta in the xda post and then the twrp

**Comment by RandomUser1321** [comment]
after I unlocked the bootloader I flashed vbmeta disabled and then flashed twrp
The old one actually flashed and after getting to twrp this happened: Device model was recognized as a M02s and the phone would just randomly close and open again and touch doesnt work
With the new version which claims the touch does work I cant get it to flash it keeps saying file analysis on odin

**Comment by mlm-games** [comment]
Hmm so it does not wrk, ill try to see abt it (currently i have final exams so might take some time)

**Comment by mlm-games** [comment]
> after I unlocked the bootloader I flashed vbmeta disabled and then flashed twrp The old one actually flashed and after getting to twrp this happened: Device model was recognized as a M02s and the phone would just randomly close and open again and touch doesnt work With the new version which claims the touch does work I cant get it to flash it keeps saying file analysis on odin

Did u try with the vbmeta img from the xda post in readme.md and then the twrp .img?

**Comment by RandomUser1321** [comment]
no its some vbmeta I found while looking in some other sites
